---

- hosts: all
  become: true
  pre_tasks:
  - name: install updates (RHEL)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install update (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php on Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php on RHEL9 OS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package (RHEL)
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install mariadb package (Ubuntu)
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    package:
      name: samba
      state: latest
